version: '3.8'

services:
  ml-service:
    build: .
    container_name: ml_service
    ports:
      - "8000:80" 
    networks:
      - app_network

  back-java:
    image: back_java_image:latest
    container_name: back_java_service
    ports:
      - "8080:8080"
    networks:
      - app_network
    depends_on:
      - ml-service

networks:
  app_network:
    driver: bridge
